#!/usr/local/bin/php
<?php
require(__DIR__ . '/vendor/autoload.php');

// Load dotenv
$dotenv = new Dotenv\Dotenv(__DIR__);
$dotenv->load();

$dbname = getenv('DB_NAME');
$user = getenv('DB_USER');
$pass = getenv('DB_PASS');

$mysqli = new mysqli("localhost", $user, $pass, $dbname);

if ($mysqli->connect_errno) {
    echo "Failed to connect to MySQL: (" . $mysqli->connect_errno . ") " . $mysqli->connect_error;
}
if (!$mysqli->query("DROP TABLE IF EXISTS `symbols`")) {
    echo "Table creation failed: (" . $mysqli->errno . ") " . $mysqli->error;
}
// Create symbols table
$sql = "CREATE TABLE `symbols` (
  `id` int(11) NOT NULL,
  `value` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci; ";
$sql.= "ALTER TABLE `symbols` ADD PRIMARY KEY (`id`); ";
$sql.= "ALTER TABLE `symbols` MODIFY `id` int(11) NOT NULL AUTO_INCREMENT; ";

if (!$mysqli->multi_query($sql)) {
    echo "Multi query failed: (" . $mysqli->errno . ") " . $mysqli->error;
} else {
	echo "Database created!";
}

?>