#!/usr/local/bin/php
<?php
	require(__DIR__ . '/vendor/autoload.php');
	require(__DIR__ . '/classes/Autoloader.php');

	// Load dotenv
	$dotenv = new Dotenv\Dotenv(__DIR__);
	$dotenv->load();

	// Get the .csv url from environment variables
    $downloadUrl = getenv('SYMBOLS_CSV_URL');
    if (!$downloadUrl) {
    	print "ERROR: Please set <SYMBOLS_CSV_URL> in your .env \n"; die();
    }

    try {
    	// Get csv file. Suppress warnings
    	$csv = @file_get_contents($downloadUrl);
    	if (!$csv) {
    		throw new Exception("ERROR: Couldn't read file from url \n");
    	}
    } catch (Exception $e) {
    	print $e->getMessage();
    }

    $data = array_map("str_getcsv", explode("\n", $csv));
    // unset($data[0]);
    $fp = fopen('data/symbols.json', 'w');
    fwrite($fp, json_encode($data));
	fclose($fp);
?>